accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("register/", views.SignUpView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

movie_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import MovieDetailView, MoviesListView, RateMovieView

app_name = 'movies'

urlpatterns = [
    path('', MoviesListView.as_view(), name='list'),
    path('<int:pk>/', MovieDetailView.as_view(), name='detail'),

    path('<int:pk>/rate/', RateMovieView.as_view(), name='rate'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    birthday = models.DateField(null=True, blank=True)
    favorite_movies = models.ManyToManyField('movies.Movie')

    def __str__(self):
        return self.username

core/models.py
from django.db import models

# Create your models here.

crew/models.py
from django.db import models


class Director(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    birthday = models.DateField(null=True, blank=True)
    country = models.ForeignKey(
        'movies.Country',
        related_name='directors',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Actor(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    birthday = models.DateField(null=True, blank=True)
    country = models.ForeignKey(
        'movies.Country',
        related_name='actors',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

movies/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

User = get_user_model()


class Movie(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(default='')
    year = models.PositiveSmallIntegerField(null=True, blank=True)
    photo = models.ImageField(upload_to='movies_photo', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    director = models.ForeignKey(
        'crew.Director',
        related_name='movies',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    actors = models.ManyToManyField(
        'crew.Actor',
        related_name='movies',
    )
    genre = models.ManyToManyField(
        'movies.Genre',
        related_name='movies',
    )
    rates = models.ManyToManyField(
        User,
        through='movies.Rate',
        related_name='rated_movies',
    )
    country = models.ForeignKey(
        'movies.Country',
        related_name='movies',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class Rate(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    stars = models.PositiveSmallIntegerField(default=0)
    date_rated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} rated for {self.movie} with {self.stars} stars'


# TODO move to core
class Country(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'countries'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2")

movies/forms.py
from movies.models import Rate, Movie
from django import forms


class RateMovieForm(forms.ModelForm):
    stars = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = Rate
        fields = ("user", "movie", "stars")

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import views as auth_django_views
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from .forms import UserRegisterForm

User = get_user_model()


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')
    form_class = UserRegisterForm
    success_message = "Registration successful"


class LoginView(SuccessMessageMixin, auth_django_views.LoginView):
    template_name = 'accounts/login.html'
    success_message = "You have successfully logged in"

    def get_redirect_url(self):
        return super().get_redirect_url() or reverse('core:home')


class LogoutView(auth_django_views.LogoutView):

    def get_next_page(self):
        messages.info(self.request, "You have successfully logged out")
        return reverse('core:home')

core/views.py
from movies.views import MoviesListView


class HomeView(MoviesListView):
    pass

crew/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from movies.models import Movie, Rate
from movies.forms import RateMovieForm
from django.contrib.auth.mixins import LoginRequiredMixin


class MoviesListView(ListView):
    model = Movie

    template_name = 'movies/list.html'
    context_object_name = 'movies'

    ordering = '-created_at'
    paginate_by = 10


class MovieDetailView(DetailView):
    model = Movie

    template_name = 'movies/detail.html'
    context_object_name = 'movie'


class RateMovieView(LoginRequiredMixin, CreateView):
    form_class = RateMovieForm
    success_url = reverse_lazy('movies:list')
    success_message = "You are rated this movie"
    template_name = 'movies/rate.html'

templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="{% url "accounts:register" %}">Create an account</a>.</p>
    </div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <p class="text-center">If you already have an account, <a href="{% url "accounts:login" %}">login</a> instead.
        </p>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <title>Movie Manager</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
<div class="container">
    {% include "header.html" %}

    <div class="row justify-content-center">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="container-fluid p-0">
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                            </button>
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="col-8">
            <br class="mt-0 mb-4">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    {% include "footer.html" %}
</div>

</body>

</html>

templates/footer.html
{#<footer class="bg-light text-center text-lg-start ">#}
{#    <!-- Grid container -->#}
{#    <div class="container p-4">#}
{#        <!--Grid row-->#}
{#        <div class="row">#}
{#            <!--Grid column-->#}
{#            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">#}
{#                <h5 class="text-uppercase">Links</h5>#}
{##}
{#                <ul class="list-unstyled mb-0">#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 1</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 2</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 3</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 4</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <!--Grid column-->#}
{##}
{#            <!--Grid column-->#}
{#            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">#}
{#                <h5 class="text-uppercase mb-0">Links</h5>#}
{##}
{#                <ul class="list-unstyled">#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 1</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 2</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 3</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 4</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <!--Grid column-->#}
{##}
{#            <!--Grid column-->#}
{#            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">#}
{#                <h5 class="text-uppercase">Links</h5>#}
{##}
{#                <ul class="list-unstyled mb-0">#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 1</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 2</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 3</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 4</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <!--Grid column-->#}
{##}
{#            <!--Grid column-->#}
{#            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">#}
{#                <h5 class="text-uppercase mb-0">Links</h5>#}
{##}
{#                <ul class="list-unstyled">#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 1</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 2</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 3</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#!" class="text-dark">Link 4</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <!--Grid column-->#}
{#        </div>#}
{#        <!--Grid row-->#}
{#    </div>#}
{#    <!-- Grid container -->#}
{##}
{#    <!-- Copyright -->#}
{#    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">#}
{#        © 2020 Copyright:#}
{#        <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>#}
{#    </div>#}
{#    <!-- Copyright -->#}
{#</footer>#}

{# TODO add this is needed #}

templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url "core:home" %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:logout" %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Welcome, {{ user.username }}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/movies/detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <h1>{{ movie.title }}</h1>
    <img src="{{ movie.photo.url }}" class="img-fluid" alt="{{ movie.title }}">

    <div class="col">
        <div class="row">
            <i class="bi bi-star-fill"></i>
            {#            <img src="{% static "images/star-fill.svg" %}" alt="star"> #}
            <span>Rate this movie: <a href="{% url "movies:rate" movie.pk %}">here</a></span>

            <p class="text">Year: {{ movie.year }}</p>
            <p class="text-dark">Director: <a href="#TODO">{{ movie.director }}</a></p>
            <p class="text-dark">Actors:</p>
            {% for actor in movie.actors.all %}
                <p class="text-dark"><a href="#TODO">{{ actor }}</a></p>
            {% endfor %}
            <p class="text-dark">Country: {{ movie.country }}</p>
            {% for genre in movie.genre.all %}
                <p class="text-dark">Genre: {{ genre }}</p>
            {% endfor %}


        </div>

        <p class="text">{{ movie.description }}</p>
    </div>
    </div>


{% endblock %}

templates/movies/list.html
{% extends "base.html" %}

{% block content %}
    <h1>This is homepage</h1>
    <div class="row">
        {% for movie in movies %}
            <div class="card" style="width: 18rem; margin: 2px">
                <img src="{{ movie.photo.url }}" class="card-img-top" alt="{{ movie.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.title }}</h5>
                    <p class="card-text">{{ movie.description|truncatechars:150 }}</p>
                    <a href="{% url "movies:detail" movie.pk %}" class="btn btn-primary">Check this movie...</a>
                </div>
            </div>
        {% empty %}
            <h2>No movies yet.</h2>
        {% endfor %}
    </div>


{% endblock %}

templates/movies/rate.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <h1>Rate movie</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Rate</button>
        </form>
    </div>

{% endblock %}